import SearchBar from "@/components/search-bar/SearchBar";
import {
  InsightsIcon,
  NewIcon,
  NotificationIcon,
  PublishedIcon,
} from "@/components/svg-icons/icons";
import SideBar from "@/screens/admin/SideBar";
import React from "react";
import adminStyles from "./admin-page.module.scss";
import { EventsDummy } from "@/utils/data/events";
import Card from "@/screens/events-card/Card";
import vote from "../../../../utils/images/star.png";
import { Event } from "@/types/eventtype";
import Head from "next/head";

const Account = () => {
  // const [activeEvents, setActiveEvents] = React.useState(Array<Event>);

  const activeEvents = EventsDummy.filter((event: Event) => {
    return event.isActive;
  });

  // console.log(activeEvents);
  const style = {
    width: "10%",
    height: "100px",
    fontSize: "0.2rem",
    padding: "0",
  };

  return (
    <>
      <Head>
        <title>UEW-Admin </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={adminStyles.container}>
        <section>
          <SideBar />
        </section>
        <section className={adminStyles.wrapper}>
          <header>
            <SearchBar />
            <div>
              <NotificationIcon />
              <InsightsIcon />
              <PublishedIcon />
              <NewIcon />
            </div>
            <h3>Welcome Owusu Benjamin</h3>
          </header>
          <div className="line"></div>

          <div className={adminStyles.activeEvents}>
            {activeEvents?.map((item, ind) => {
              return (
                <Card
                  key={ind}
                  ImageUrl={""}
                  imgAlt={""}
                  title={item.eventTitle}
                  styles={style}
                  isActive={item.isActive}
                />
              );
            })}
          </div>

          <footer></footer>
        </section>
      </main>
    </>
  );
};

export default Account;
